image: nrayamajhee/arch-wasm-pack

pages:
  stage: deploy
  script:
  - ./build b f
  #- wasm-pack test --headless --chrome
  - mv frontend/www/dist ../public
  artifacts:
    paths:
    - public
  only:
  - master